image: gradle:jdk11-slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/
    - build/docs/

build:
  stage: build
  script: gradle --build-cache --full-stacktrace assemble

test:
  stage: test
  script:
    - gradle --build-cache --full-stacktrace check
    - cat build/reports/jacoco/test/html/index.html

.pages:
  only:
    - tags
  stage: deploy
  script:
    - gradle commandlerdoc
    - mv build/docs/commandlerdoc public
  artifacts:
    paths:
      - public
  cache:
    policy: pull
    paths:
      - build/docs/
