application:
  name: Example
commandler:
  integration:
    - "org.elypia.commandler.console.ConsoleIntegration"
  dispatcher:
    - "org.elypia.commandler.dispatchers.StandardDispatcher"
  controller:
    - type: "org.elypia.example.UtilityController"
      name: "Utilties"
      help: "Random utilities to add some quick generic functionality."
      properties:
        - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
          value: "util"
      commands:
        - method: "ping"
          name: "ping!"
          help: "Check if the application is still responsive!"
          static: "true"
          properties:
            - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
              value: "ping"
        - method: "sum"
          name: "Sum"
          help: "Add up a bunch of integer numbers."
          static: "true"
          properties:
            - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
              value: "sum, add"
