application:
  name: "Prefix Example"
commandler:
  dispatcher:
    - class: "org.elypia.commandler.dispatchers.StandardDispatcher"
      prefix:
        - ">"
  controller:
    - type: "org.elypia.example.prefix.UtilityController"
      name: "Utilities"
      description: "Random utilities to add some quick generic functionality."
      property:
        - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
          value: "utils"
      command:
        - method: "ping"
          name: "ping!"
          description: "Check if the application is still responsive!"
          static: "true"
          property:
            - name: "org.elypia.commandler.dispatchers.StandardDispatcher.aliases"
              value: "ping"
